### ISSUE TITLE
Create updated Game Plan/Solicit feedback

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#147]
The original game plan for Helium was largely based on the Book Info app from Istio. Now it seems some of the micro services may not be necessary.

Update the [Game Plan](https://teams.microsoft.com/l/file/421EB510-664E-4809-8978-7235F7CE7A26?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&fileType=docx&objectUrl=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FWMTCSEEngagement%2FShared%20Documents%2FHelium%20EntRef%20App%2FHelium_GamePlan.docx&baseUrl=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FWMTCSEEngagement&serviceName=teams&threadId=19:891f80babe75405e9edbb49ae1f07666@thread.skype&groupId=f36284b8-cb9d-42b4-947e-9ac3e141aa74) with the new goals of the project.

- [ ] #156 Manual deployment infra for Helium - Will

- [ ] #182 Logging and Telemetry update - Janani

- [ ] #191 Overall design and architecture - Janani
