### ISSUE TITLE
Reference App

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#5]
Build a REST API MVP that demonstrates the proper use of CosmosDB, Azure 
Monitor, App Insights, and Web Apps for Containers.

- [x] #1 Scaffold project layout
- [x] #2 Create simple Mocha config
- [ ] #3 Create basic Dockerfile, consider multi stage value-add
- [x] #4 Stub out endpoint routes/controllers
