### ISSUE TITLE
CosmosDB

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#6]
We need to understand the best practices for using CosmosDB in NodeJS apps. We also need to understand the best practices for modeling a user rating system in CosmosDB.

Determine the configuration needed to set up a CosmosDB with multi-region active-active support.

- [x] #10 Determine what data to import
- [ ] #12 Create data model for movie storage
- [x] #11  Write example snippets for CRUD operations
- [ ] #23 Create Script for Importing CosmosDB data
- [x] #24 Document Cost Analysis for CosmosDB
- [ ] #25 Enable Monitoring for CosmosDB
- [x] #26 Create Typescript DAL for CosmosDB
- [x] #27 Create CosmosDB Readme
- [ ] #47 Add logging and metrics to CosmosDB client
