### ISSUE TITLE
App Insights

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#8]
Gather best practices for using Azure App Insights in a NodeJs service and implement it in the reference REST app.

- [x] #13 App Insights discovery
- [x] #14 Configure REST app to use
- [x] #15 Implement telemetry tracking
- [x] #16 Implement dependency tracking
