### ISSUE TITLE
Web Apps for Containers

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#9]
Ensure the reference app uses the Web Apps for Containers platform properly.

- [x] #18 Web Apps for Containers discovery
- [x] #20 Write instructions or scripts necessary to deploy the reference app to WAC
- [ ] #21 Deploy development instance of reference app to WAC

**Comment by WilliamMortlMicrosoft** [comment]
Using: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-docker-go

I have deployed a container into Web Apps for #18

**Comment by WilliamMortlMicrosoft** [comment]
#20 is in progress

**Comment by WilliamMortlMicrosoft** [comment]
#21 will be implemented by way of DevOps
